### ISSUE TITLE
Question: Is the information entered in the equipment "User defined data" form available?

### ISSUE THREAD

**Issue by DaAntidote** [poctob/OSTEquipmentPlugin#24]
When opening a newly entered equipment I expected it to populate the form or have the data displayed somewhere that was entered with "User defined data" custom form.

Is it available / stored with the asset?

There are some basic elements missing from the Equipment definitions I feel;
Description
Location
Install Date
Serial Number.

I have added these and a few others to a custom form which appears when adding new equipment but can't seem to see how I can recycle them anywhere...?

**Comment by poctob** [comment]
They suppose to show up with the asset on view/edit page.  This functionality is broken in the release due to the differences between OST 1.9.2 and 1.9.3.  The fix was committed to the source tree.

https://github.com/poctob/OSTEquipmentPlugin/commit/3e54d0cb8813dcd54b73f4764e4b6872783748af#diff-d41d8cd98f00b204e9800998ecf8427e
