### ISSUE TITLE
Add Ticket Subject column to Recurring Tickets Page

### ISSUE THREAD

**Issue by DaAntidote** [poctob/OSTEquipmentPlugin#25]
Enhancement
It would be helpful to have a brief description of the recurring tickets purpose on the recurring ticket page. Perhaps add the ticket subject as a column? 
And or make the ticket ID a hyperlink to open the ticket in a new window.

**Comment by poctob** [comment]
If you notice, https://github.com/poctob/OSTEquipmentPlugin/issues/2, is still open.  This functionality is not complete yet.  There are some major issues related to handling tickets and scheduling.  OSTicket core doesn't provide an easy way to copy tickets or to schedule recurring jobs.  As you've noticed, the current work around is to re-open an existing ticket instead of generating a new one with the same parameters.  Actually, you've been duped into thinking that the tickets are being re-opened on schedule.  In fact, this functionality only works when there is an active user in the system.  If you never open a webpage, nothing will get scheduled. 

The current direction is to outsource this functionality into the databases as a recurring event and to limit the dependency on OSTicket code as much as possible.

**Comment by DaAntidote** [comment]
Ok thanks for the info. Just to clarify if someone isn't logged in at the scheduled time then the recurrence will not be triggered?

**Comment by poctob** [comment]
Yes, basically there has to be some kind on activity on the page.  Even if it is
as simple as loading the frontend.

> On August 16, 2014 at 10:37 PM FluffyLightEngineering

**Comment by DaAntidote** [comment]
Its way over my head, but perhaps investigate how the SLA overtime alert occurs. I seem to get emails advising over overdue tickets even though nobody is using the system... Perhaps that same process can be utilised.

**Comment by poctob** [comment]
Well that the whole problem with builtin functionality.  The events are firing at seemingly random intervals and seem to be too far in between.  We need something more structured, that occurs regularly.  I think that the database is a way to go.
